// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Chain = require("./Chain.bs.js");
var Express = require("express").default;
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var BodyParser = require("body-parser");

var sockets = [];

function connect(peers) {
  Belt_Array.forEach(peers, (function (param) {
          
        }));
}

function init(param) {
  var app = Express();
  app.use(function (prim) {
        return BodyParser.json(prim);
      });
  app.get("/chain", (function (param, response) {
          response.send(JSON.stringify(Chain.main_chain));
        }));
  app.post("/mine", (function (request, response) {
          var new_block = Chain.generate(request.body);
          Chain.add(new_block);
          console.log("Block added" + Belt_Option.getExn(JSON.stringify(new_block)));
          response.send(undefined);
        }));
  app.get("/peers", (function (param, response) {
          response.send(Belt_Array.map(sockets, (function (socket) {
                      return socket.remote_addr + ":" + socket.remote_port;
                    })));
        }));
  app.post("/add_peer", (function (_request, response) {
          response.send(undefined);
        }));
  console.log("Listening http on port: " + String(3001));
  return app.listen(3001);
}

var http_port = 3001;

exports.http_port = http_port;
exports.sockets = sockets;
exports.connect = connect;
exports.init = init;
/* Chain Not a pure module */
