// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Crypto_JS = {};

var Body_Parser = {};

var $$WebSocket = {};

exports.Crypto_JS = Crypto_JS;
exports.Body_Parser = Body_Parser;
exports.$$WebSocket = $$WebSocket;
/* No side effect */
